### ISSUE TITLE
How can I use is as instance. ?

### ISSUE THREAD

**Issue by thunderwin** [Gomah/nuxt-shopify#188]
How can I use it as an instance? 

I need dynamically change the endpoint and token base on user request.  

how could I do it.. please.

**Comment by Gomah** [comment]
Hey @thunderwin, do you want to override the client or use multiple clients?

I added the `buildClient` functionality in 1.8.1:

```js
methods: {
    async change() {
      this.$shopify.buildClient({ domain: 'newdomain.shopify.com', storefrontAccessToken: 'newAccessToken' });

      const products = await this.$store.$shopify.product.fetchAll();
    }
}
```

Let me know if it works for you

**Comment by DavidTParks** [comment]
How would I use this in the nuxt config file to generate the dynamic routes for some of my products? 
I'm importing via `const shopify = require('nuxt-shopify');`

and trying to generate the routes by doing
`generate: {
    async routes() {
      shopify.buildClient({ domain: 'MY_DOMAIN', storefrontAccessToken: process.env.SHOPIFY_TOKEN });
      const products = await shopify.product.fetchAll();
      const routes = products.map(product => `/candles/${product.id}`)

      return ['/'].concat(routes)
    }
  },`

but receive an error that `shopify.buildClient` is not a function is not defined.

**Comment by Gomah** [comment]
@DavidTParks, the `nuxt-shopify` package does not export the client, for this purpose I'd suggest using a module to generate your extra routes:


```js
// modules/generate-product-routes.js
export default async ctx => {
  this.nuxt.hook('generate:before', async (nuxt, generateOptions) => {
    const products = await this.$shopify.product.fetchAll();
    const routes = products.map(product => `/candles/${product.id}`)

    generateOptions.routes = generateOptions.routes
      ? generateOptions.routes.concat(routes)
      : routes;
  });
};
```

```js
// nuxt.config.js
{
  modules: ['~/generate-product-routes.js'],
}
```

**Comment by DavidTParks** [comment]
@Gomah thank you very much!
