### ISSUE TITLE
Mode `../../lib/module` not found.

### ISSUE THREAD

**Issue by xSketchy0** [Gomah/nuxt-shopify#261]
Hey,

I'm having a problem with cloning the repository and actually getting it to work. I've cloned the repo with `git clone "repo URL"`, then I installed the dependencies with `yarn install`. After that I tried to run `yarn dev` or `npm run dev`, but it throws the following error.

```
PS M:\nuxt-shopify> yarn dev
yarn run v1.22.4
$ nuxt test/fixture

 FATAL  Module ../../lib/module not found. Please ensure ../../lib/module is in dependencies and installed.                                                                                                                        14:23:42  

  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:182:17)
  at promise.then (node_modules\@nuxt\utils\dist\utils.js:1803:43)


   ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                      │
   │   ✖ Nuxt Fatal Error                                                                                                 │
   │                                                                                                                      │
   │   Error: Module `../../lib/module` not found. Please ensure `../../lib/module` is in `dependencies` and installed.   │
   │                                                                                                                      │
   ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Anyone know how to solve this?

Much appreciated!

**Comment by Gomah** [comment]
Hey @xSketchy0,

You need to build the `lib` folder using `npm run build` or `yarn build` 👌

**Comment by xSketchy0** [comment]
> Hey @xSketchy0,
> 
> You need to build the `lib` folder using `npm run build` or `yarn build` 👌

Oh wow now I feel stupid, totally forgot about that command haha! One more thing though as I'm not really experienced with using Shopify + Nuxt.js or Nuxt.js in general. How would I go about actually running this theme I'd be building in Nuxt.js on Shopify?

Would I have to run these Nuxt.js files on a seperate server and disable the shopify storefront on the ".myshopify.com" URL? Or is there a way of compiling the Nuxt.js into a usable Liquid theme?

**Comment by xSketchy0** [comment]
I believe this store was also built with Nuxt.js, but the routes are all the same for example "patta.nl/collections/..", "patta.nl/pages/.." etc, I'm not sure if they're running it on a seperate server and using identical routes or if they're just running Nuxt.js on Shopify

**Comment by Gomah** [comment]
> Would I have to run these Nuxt.js files on a separate server and disable the Shopify storefront on the ".myshopify.com" URL? Or is there a way of compiling the Nuxt.js into a usable Liquid theme?

Yes, this module is aimed to use a separate application using Nuxt.js with Shopify's storefront API.

Indeed, it looks like patta.nl is still using Shopify and a custom theme, but I could be werong
