### ISSUE TITLE
Get translation of products

### ISSUE THREAD

**Issue by esplito** [Gomah/nuxt-shopify#313]
I'm currently working on a project where we need to display product content from Shopify in two different languages (English & Swedish), but I can't find anywhere if this is actually accessible in this module. 

I've added a third-party app on Shopify and translated one product, but I can't see any "translation"-key or similar on the product object. The Shopify documentation says that product description and title should be available in the Storefront API: [https://shopify.dev/tutorials/manage-app-translations-with-admin-api#storefront-api-translation-resources](https://shopify.dev/tutorials/manage-app-translations-with-admin-api#storefront-api-translation-resources) 

It should be possible to get translated content according to the JS Buy SDK documentation as well: [https://github.com/Shopify/js-buy-sdk#initializing-the-client](https://github.com/Shopify/js-buy-sdk#initializing-the-client)

I've tried to add:

`language: 'sv-SE'` 

to the nuxt config, but nothing happens.

Is it possible to get the product translations and if so, how?

Thanks,
Emil

**Comment by Gomah** [comment]
Thanks @esplito, should be fixed in v1.30.3!
