### ISSUE TITLE
Fetch more than 20 products by Collection

### ISSUE THREAD

**Issue by ianfortier** [Gomah/nuxt-shopify#37]
It is possible to return more than 20 products using the collection id?
I tried to use fetchNextPage without any success. If anymore can share a snippet that would be great!

Thanks!

**Comment by Gomah** [comment]
Hey @ianfortier 

Looks like it's an issue with the shopify-buy SDK:

https://github.com/Shopify/js-buy-sdk/issues/472
https://github.com/Shopify/js-buy-sdk/issues/433#issuecomment-353181172

**Comment by Gomah** [comment]
@ianfortier shopify-buy 2.8.1 (nuxt-shopify 1.6.1) [introduces](https://github.com/Shopify/js-buy-sdk/commit/ab33b2a32134f8827e718bd16d059019485e8166) an optional param for specifying the number of products to return.

You can now do:

```ts

// Fetch a single collection by ID, including its products
const collectionId = 'Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzM2OTMxMjU4NA==';

// Set a parameter for first x products, defaults to 20 if you don't provide a param

this.$shopify.collection.fetchWithProducts(collectionId, { productsFirst: 30 }).then(collection => {
  // Do something with the collection
  console.log(collection);
  console.log(collection.products);
});
