### ISSUE TITLE
fetchNextPage() Collection Pagination?

### ISSUE THREAD

**Issue by mixedfeelings** [Gomah/nuxt-shopify#427]
Hello, all!

I am attempting to implement collection pagination in the form of an infinite scroll, but I am having difficulty with fetchNextPage. fetchWithProducts() works perfectly as described in the project readme, but trying to extend the client to use fetchNextPage, i always get a _TypeError: node is undefined_ error on that line. I am following the migrate documentation from the storefront migration guide: https://github.com/Shopify/js-buy-sdk/blob/master/tutorials/MIGRATION_GUIDE.md#pagination 

Here is my method:

```
            fetchCollection() {
                let productsForCollection;                
                this.$shopify.collection.fetchWithProducts(this.id, { productsFirst: 12 }).then((collection) => {
                    productsForCollection = collection.products;
                    console.log(productsForCollection);

                });
                this.$shopify.fetchNextPage(productsForCollection).then((nextPageOfProducts) => {
                    console.log(nextPageOfProducts);
                });
            },
```

Has anyone successfully implemented pagination on their nuxt-shopify project and can give me any pointers on what i might be doing wrong?

**Comment by Gomah** [comment]
Hey @mixedfeelings, just added an example in the fixtures:

https://github.com/Gomah/nuxt-shopify/blob/master/test/fixture/pages/collection-pagination.vue

Let me know if that's helpful

**Comment by mixedfeelings** [comment]
WOW! Incredibly, amazingly helpful! I can't thank you enough for both Nuxt-Shopify and this great solution!
