### ISSUE TITLE
Fetch id of productVariant

### ISSUE THREAD

**Issue by jo-elbdev** [Gomah/nuxt-shopify#466]
I am having issues in using the` $shopify.checkout.addLineItems` method. When I fetch a product, the id's of my productVariants look like this:

```
"variants": [
      {
        "id": 37347204038813,
        "product_id": 5909234516125,
        "admin_graphql_api_id": "gid://shopify/ProductVariant/37347204038813"
      },
]
```

But none of these ids work here:

```
  async addCartItem(state, {selectedVariantId}) {
    const lineItemsToAdd = [
      {
        variantId: selectedVariantId, // either id or product_id
        quantity: 1
      }];

    await this.$shopify.checkout.addLineItems(this.app.$checkout.getCheckoutId(), lineItemsToAdd)
      .then(checkout => {
        console.log(checkout);
      }).catch((e) => {
        console.log(e);
      });
  },
```

Error message:

`Error: [{"message":"Variable $lineItems of type [CheckoutLineItemInput!]! was provided invalid value for 0.variantId (Invalid global id `5909234516125`)","locations":[{"line":1,"column":3245}],"extensions":{"value":[{"variantId":5909234516125,"quantity":1}],"problems":[{"path":[0,"variantId"],"explanation":"Invalid global id `5909234516125`","message":"Invalid global id `5909234516125`"}]}}]`

Of course, I noticed that the variantId looks different, then the ID I am getting. But nowhere is written, where I can find the acutal "global" id.

Also, fetching the variant by id or product_id also does not work.

**Comment by Gomah** [comment]
Interesting, I think that might be related to the Shopify SDK.

What version of the Storefront API are you using? 
Usually, variant Ids look like the following: `Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8yOTEwNjAyMjc5Mg==`, unless you're using a different API than the Shopify's storefront API?

As a short fix, you could potentially stringify the variantId?

```ts
async addCartItem(state, {selectedVariantId}) {
    const lineItemsToAdd = [
      {
        variantId: selectedVariantId.toString(), // either id or product_id
        quantity: 1
      }];

    await this.$shopify.checkout.addLineItems(this.app.$checkout.getCheckoutId(), lineItemsToAdd)
      .then(checkout => {
        console.log(checkout);
      }).catch((e) => {
        console.log(e);
      });
  },
```

Let me know if it works!

**Comment by simonhrogers** [comment]
@jo-elbdev – I was confused by this too. This is because the ID you’re using came from Shopify’s admin API rather than the storefront API. You can encode like so:

```
      this.$store.dispatch("checkout/addLineItem", {
        selectedVariantId:  btoa(`gid://shopify/ProductVariant/${this.selectedVariantId}`),
        quantity: 1
      });
```
