### ISSUE TITLE
Missing the product tags

### ISSUE THREAD

**Issue by febdao** [Gomah/nuxt-shopify#487]
Hi Gomah,
I would like to get the product `tags`, but can't get it from the API

<img width="358" alt="Screen Shot 2021-01-21 at 11 31 12 am" src="https://user-images.githubusercontent.com/7425119/105257578-2d8bc700-5bdc-11eb-85cf-c79e0d3adcf5.png">

Could you please help me to check it?
Thank you so much!

**Comment by Gomah** [comment]
Hey @febdao , did you try using the `unoptimized` setting?

**Comment by febdao** [comment]
thanks @Gomah for answering,

I already enabled the `unoptimized` settings:
![Screen Shot 2021-01-21 at 1 35 37 pm](https://user-images.githubusercontent.com/7425119/105272550-b2cba780-5bed-11eb-9973-67edaa90bd65.png)

**Comment by Gomah** [comment]
You can use the following example if you want to add extra fields:

```ts
// Build a custom products query using the unoptimized version of the SDK
const productsQuery = this.$shopify.graphQLClient.query((root) => {
  root.addConnection('products', { args: { first: 10 } }, (product) => {
    product.add('tags'); // Add fields to be returned
  });
});

// Call the send method with the custom products query
const result = await this.$shopify.graphQLClient.send(productsQuery);

// Do something with the products
console.log({ products: result.model });
});


```

Example from: https://github.com/Shopify/js-buy-sdk#fetching-products-1

**Comment by febdao** [comment]
Thanks @Gomah 
I can fetch the `tags` from `products`.
How about the `tags` from `product detail`? Can we use the same query?

**Comment by Gomah** [comment]
Not sure but I assume it would be similar:

```ts
// Build a custom products query using the unoptimized version of the SDK
const productQuery = this.$shopify.graphQLClient.query((root) => {
  root.addConnection('product', { args: {} }, (product) => {
    product.add('tags'); // Add fields to be returned
  });
});

// Call the send method with the custom product query
const result = await this.$shopify.graphQLClient.send(productQuery);

// Do something with the product
console.log({ products: result.model });
```

**Comment by Gomah** [comment]
@febdao I assume it's fixed? Closing for now
