### ISSUE TITLE
Fetching Pages from Shopify

### ISSUE THREAD

**Issue by robmellett** [Gomah/nuxt-shopify#61]
Hey @Gomah,

Thank you for your amazing work with this plugin.  Any ideas on how we might be able to access Pages from Shopify?

I've had a look at the Shopify Buy SDK, and unfortunately Shopify haven't included a PageResource internally.  This is the query we need to run.

```javascript
const query = $shopify.graphQLClient.query((root) => {
      root.addConnection('pages', { args: { first: 10 }}, (page) => {
        page.add('title');
        page.add('body');
      });
    });
let page = await $shopify.graphQLClient.send(query).then(({ model, data }) => {
      return data;
    });
```
Upon running the above snippet I'm getting an error `No field of name "pages" found on type "QueryRoot" in schema`.

And this seems to be because the Pages type isn't included in the Shopify `import Client from 'shopify-buy';` build.  I've hacked together a quick example using `import Client from 'shopify-buy/index.unoptimized.umd';` and I can see my above query working.

Any ideas on how we might get the unoptimised Shopify SDK working with your plugin?  Would it be possible to create a speparate branch using the unoptimised version?

Thanks mate,
Rob

**Comment by Gomah** [comment]
Hey @robmellett,

I didn't know about the `unoptimized` build, that's great, maybe I don't need a Headless CMS on the side if I can fetch Shopify pages content!

I just added this functionality in the `1.6.0` release, simply add `unoptimized: true` to your Shopify config in the nuxt.config.js file.

Let me know if you encounter any issues

**Comment by robmellett** [comment]
Amazing!  It works like a charm.  I owe you a beer internet friend :)

**Comment by ideacco** [comment]
@robmellett 
Wow, your example code helped a lot! ! ! thank you very much
