### ISSUE TITLE
Unable to find `quantityAvailable` on variants – how can I get count stock?

### ISSUE THREAD

**Issue by simonhrogers** [Gomah/nuxt-shopify#734]
Hi there, 

I’m not sure if I’m missing something, but this isn’t coming through on my requests, even with `unoptimised: true` set in my `nuxt.config.js` file. 

I literally just need to query stock level and product/variant id as I am importing product data from Shopify to Sanity, but have been using: `this.$shopify.product.fetchAll()`. 

Thanks so much for your work on this,

Simon

**Comment by simonhrogers** [comment]
I’ve been able to use the Buy SDK directly as a workaround like so:

`import Client from 'shopify-buy/index.unoptimized.umd';`

I think using the unoptimised build allows you to expand queries, and from what I’ve understood that’s required in order to retrieve product stock. I’m not sure if I’m being silly but it seems essential to me to know the available quantity of an item before adding something to the cart? Is there an alternative method people are relying upon for this? Bad response when trying to add an additional item to the cart maybe?

```
    const productsQuery = shopify.graphQLClient.query((root) => {
      root.addConnection("products", { args: { first: 10 } }, (product) => {
        product.add("title");
        product.addConnection("variants", { args: { first: 10 } }, (variant) => {
          variant.add("title");
          variant.add("quantityAvailable");
        });
      });
    });

    shopify.graphQLClient.send(productsQuery).then(({ model, data }) => {
      model.products.forEach((product) => {
        product.variants.forEach((variant) => {
          // Inventory available for the variant
          console.log(product.title, variant.title, variant.quantityAvailable);
        });
      });
    });
```

**Comment by Gomah** [comment]
Hey @simonhrogers,

You're right, unfortunately, the `shopify-buy` is not including `quantityAvailable` for the `ProductVariant`, looks like they haven't been updating their Fragment for a while: https://github.com/Shopify/js-buy-sdk/tree/master/src/graphql

The next version of `nuxt-shopify` will provide a new SDK to solve this problem ✌🏻

**Comment by rcobiella** [comment]
Hey @Gomah,

Apologies for reopening this. I'm having the same problem when trying to retrieve `media` to get the product videos and not only the images, and it's become an impossible task. For what I see it's the same problem with the Fragment not being updated, right?

When is the new `nuxt-shopify` version due to be released? Really looking forward to it!

**Comment by Gomah** [comment]
Hey @rcobiella,

Correct, you might need to update the query fields as @simonhrogers did.

No ETA for the new version yet, sorry!

**Comment by rcobiella** [comment]
> Hey @rcobiella,
> 
> Correct, you might need to update the query fields as @simonhrogers did.
> 
> No ETA for the new version yet, sorry!

Hey! Yeah, I tried updating the fragment myself after my post and now it's retrieving everything correctly. Thank you for the tip!

**Comment by simonhrogers** [comment]
Glad it helped. And small world – on Friday Tom Baber was showing my the Drama typeface he was making for a site you are working on @rcobiella – love your work!

**Comment by rcobiella** [comment]
> simonhrogers

Small world indeed – Thank you so much, really appreciate it!
